# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c1d83fe44a47a5d5a67a36def825430bad260d24bd85fc33ecc857a09179bd5647b20bd94eeb7593258ee2b3091f34292aea9947f336f0781fad5ffc47316e

test:
  secret_key_base: 6e04e2db2cc9750ab186a6ccfbda41cde94a9823d868da3ec556288d3521ac76ec4bc18303dd51a8f285fbd745eb41d89999bcd9a5b3838efe20d10d0efb5485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
